### ISSUE TITLE
Absolute path requirement on Filebase SDK

### ISSUE THREAD

**Issue by chimmykk** [filebase/filebase-sdk#9]
Why is there a need of absolute path when uploading folder?
```
async function uploadFiles() {
  var filesArray = [];
  var path ='';

  try {
    const { files } = await rfs.read(path);
    files.forEach(file => {
      filesArray.push({ path: file, content: fs.createReadStream(file) });
    });
```
as we used absolute path, the ipfs indexes the whole directory of the path, 

Reproducing something like
'User/test/Desktop/haha/filebase/upload'
on the var path

when uploaded gives an index of ipfs.filebase.io/ipfs/bafybeiasq6xemclt7bxzwk3v2gq/User/test/Desktop/haha/filebase/upload

Any solution to fix this issue?

**Comment by jtsmedley** [comment]
The path should be the virtual path within the IPFS folder/directory.  Any contents in that object will be saved at that virtual path.  We have applied an update though to automatically add the root / if a relative path is passed in though for convienence.

**Comment by chimmykk** [comment]
okay LGTM!
